# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- ci

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"

steps:
- task: UseDotNet@2
  displayName: "Install .NET 5"
  inputs:
    version: '5.0.x'
    includePreviewVersions: true # Required for preview versions

- task: UseDotNet@2
  displayName: "Install .NET 3"
  inputs:
    version: '3.0.x'
    packageType: runtime

- task: DotNetCoreCLI@2
  displayName: "DotNet restore"
  inputs:
    command: 'restore'
- task: DotNetCoreCLI@2
  displayName: "DotNet build $(buildConfiguration)"
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  
- task: DotNetCoreCLI@2
  displayName: "DotNet test ($(buildConfiguration))"
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "DotNet pack ($(buildConfiguration))"
  inputs:
    command: pack
    arguments: '--packageVersion $(version) --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishBuildArtifacts@1
  displayName: "DotNet publish"
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'RandExp'